berita/urls.py
from django.conf.urls import url

from berita import views

urlpatterns = [
    url(r'^$', views.lihat_semua_berita, name='semua_berita'),
    url(r'^detail/(?P<berita_id>\d+)/$', views.lihat_berita, name='sebuah_berita'),
]

dokumen/urls.py
from django.conf.urls import url

from dokumen import views

urlpatterns = [
    url(r'^$', views.daftar_dokumen, name='dokumen'),
    url(r'^download/(?P<dok_id>\d+)/$', views.download_dokumen, name='download'),
    url(r'^upload/$', views.upload_dokumen, name='upload'),
    url(r'^peta_dasar$', views.peta_dasar, name='peta_dasar'),
    url(r'^peta_rencana$', views.peta_rencana, name='peta_rencana'),
]

simtaru_kabbdg/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', views.profile_view, name='profile'),
    url(r'^grafik/', views.grafik_view, name='grafik'),
    url(r'^kontak/', views.kontak_view, name='kontak'),
    url(r'^peta/', include('lihat_peta.urls', namespace='peta')),
    url(r'^kuisioner/', include('kuisioner.urls', namespace='kuisioner')),
    url(r'^dokumen/', include('dokumen.urls', namespace='dokumen')),
    url(r'^berita/', include('berita.urls', namespace='berita')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dokumen/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Dokumen(models.Model):
    berkas = models.FileField(upload_to='dokumen')
    upload_by = models.ForeignKey(User)
    tgl_upload = models.DateTimeField(verbose_name="Tanggal Upload")
    total_download = models.IntegerField(verbose_name="Jumlah Download", default=0)
    berkas_publik = models.BooleanField(verbose_name="Untuk Publik", default=False)

    class Meta:
        ordering = ('-tgl_upload',)

dokumen/forms.py
from django import forms


class DokumenForm(forms.Form):
    docfile = forms.FileField(
        label='Pilih File'
    )
    berkas_publik = forms.BooleanField(label='Untuk Publik')

dokumen/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q
from .models import Dokumen
from .forms import DokumenForm
# Create your views here.


@login_required(login_url='/kuisioner')
def daftar_dokumen(request):
    user = request.user
    context = {}
    doc = False
    if user.is_authenticated():
        # cari dokumen yang di upload oleh user dan yang berupa publik
        doc = Dokumen.objects.all().filter(Q(upload_by=user.id) | Q(berkas_publik=True))
    elif user.is_superuser:
        doc = Dokumen.objects.all()
    else:
        # untuk tamu
        context['tamu'] = True
    if doc:
        context['doc'] = doc
    return render(request, 'dokumen/dokumen.html', context)


@login_required(login_url='/kuisioner')
def upload_dokumen(request):
    if request.method == 'POST':
        form = DokumenForm(request.POST, request.FILES)
        if form.is_valid():
            d = Dokumen.objects.create(
                berkas=request.FILES['docfile'],
                upload_by=request.user,
                tgl_upload=datetime.datetime.now(),
                berkas_publik=form.cleaned_data.get('berkas_publik', False)
            )
            d.save()
            # Redirect to the document list after POST
            return HttpResponseRedirect('/dokumen')
    else:
        form = DokumenForm()  # A empty, unbound form

    # Load documents for the list page

    # Render list page with the documents and the form
    return render(request, 'dokumen/upload.html', {'form': form})


@login_required(login_url='/kuisioner')
def download_dokumen(request, dok_id):
    group = request.user.groups.all()[0]
    d = get_object_or_404(Dokumen, pk=dok_id, group=group)
    d.total_download += 1
    d.save()
    return HttpResponseRedirect(d.berkas.url)


def peta_rencana(request):
    return render(request, 'dokumen/peta_rencana.html')


def peta_dasar(request):
    return render(request, 'dokumen/peta_dasar.html')

dokumen/templates/dokumen/dokumen.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% load staticfiles %}
{% block title %}
    Download
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-1.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="{% url 'dokumen:peta_dasar' %}">Download Peta Dasar</a></h4>


            </div> <!-- /.team-member -->

        </div>
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-3.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="{% url 'dokumen:peta_rencana' %}">Download Peta Rencana</a></h4>

            </div> <!-- /.team-member -->

        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-4.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="http://23.244.65.219/simtaru.kabbdg/download/dokumen/01.%20BUKU%20RENCANA%20RTRW.rar">BUKU RENCANA RTRW</a></h4>


            </div> <!-- /.team-member -->

        </div>
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-4.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="http://23.244.65.219/simtaru.kabbdg/download/dokumen/02.%20SLHD.rar">SLHD</a></h4>

            </div> <!-- /.team-member -->

        </div>
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-4.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="http://23.244.65.219/simtaru.kabbdg/download/dokumen/03.%20KLHS%20RTRW.rar">KLHS RTRW</a></h4>

            </div> <!-- /.team-member -->

        </div>
        <div class="col-md-3 col-sm-6">
            <div class="team-member">
                <div class="thumnail">
                    <img src="{% static 'simtaru_kabbdg/assets/images/team/member-4.jpg' %}" alt="" class="cause-img">

                </div>
                <h4 class="member-name"><a href="http://23.244.65.219/simtaru.kabbdg/download/dokumen/04.%20BUKU%20PUTIH.rar">BUKU PUTIH</a></h4>

            </div> <!-- /.team-member -->

        </div>
    </div>
    <br/>
    {% if not tamu %}
        <h2 class="title-style-2">Download Dokumen<span class="title-under"></span></h2>
        {% if doc %}
            <table class="table table-style-1">
                <thead>
                    <tr>
                        <th>File</th>
                        <th>Tanggal Upload</th>
                        <th>Jumlah Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in doc %}
                        <tr>
                            <td><a href="{% url 'dokumen:download' d.id %}">{{ d.berkas.name }}</a></td>
                            <td>{{ d.tgl_upload|date:"d/m/y H:i" }}</td>
                            <td>{{ d.total_download }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3>Belum ada dokumen yang diunggah</h3>
        {% endif %}
    {% endif %}
{% endblock content %}

dokumen/templates/dokumen/peta_dasar.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% block title %}
    Download Peta Dasar
{% endblock title %}

{% block content %}
    <h2 class="title-style-2">Download Peta Dasar <span class="title-under"></span></h2>
    <table class="table table-style-1">
        <thead>
        <tr>
          <th>#</th>
          <th>Nama File</th>
          <th>Ukuran File</th>
          <th>Aksi</th>
        </tr>
      </thead>
        <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Orientasi Wilayah Kabupaten Bandung</td>
          <td>6 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/1%20Orientasi%20Wilayah%20Kabupaten%20Bandung.jpg" target="_blank" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Administrasi Kabupaten Bandung</td>
          <td>18 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/2%20Administrasi%20Kabupaten%20Bandung.jpg" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Morfologi Kabupaten Bandung</td>
          <td>17.1 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/4%20Morfologi%20Kabupaten%20Bandung.jpg" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td>Tata Guna Lahan Kabupaten </td>
          <td>23.3 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/5%20Tata%20Guna%20Lahan%20Kabupaten%20.jpg" target="_blank" target="_blank">download </a></td>
        </tr>

        <tr>
          <th scope="row">5</th>
          <td>Sebaran Penduduk</td>
          <td>17.3 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/6%20Sebaran%20Penduduk.jpg" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">6</th>
          <td>Rawan Bencana Gunung Berapi</td>
          <td>18.6 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/7%20Rawan%20Bencana%20Gunung%20Berapi.jpg" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">7</th>
          <td>Rawan Bencana Gempa Bumi</td>
          <td>19.2 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/8%20Rawan%20Bencana%20Gempa%20Bumi.jpg" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">8</th>
          <td>Rawan Bencana Gerakan Tanah</td>
          <td>21.1 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/9%20Rawan%20Bencana%20Gerakan%20Tanah.jpg" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">9</th>
          <td>10 Rawan Bencana Banjir</td>
          <td>18.8 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/10%20Rawan%20Bencana%20Banjir.jpg" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">10</th>
          <td>Kawasan Resapan Air</td>
          <td>17.7 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20DASAR%20KAB.%20BANDUNG/11%20Kawasan%20Resapan%20Air.jpg" target="_blank">download </a></td>
        </tr>
        </tbody>
    </table>
{% endblock content %}

dokumen/templates/dokumen/peta_rencana.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% block title %}
    Download Peta Rencana
{% endblock title %}

{% block content %}
    <h2 class="title-style-2">Download Peta Rencana <span class="title-under"></span></h2>
    <table class="table table-style-1">
        <thead>
        <tr>
          <th>#</th>
          <th>Nama File</th>
          <th>Ukuran File</th>
          <th>Aksi</th>
        </tr>
      </thead>
        <tbody>
        <tr>
          <th scope="row">1</th>
          <td>1 Struktur Ruang</td>
          <td>8.24 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20RENCANA/1%20Struktur%20Ruang.jpg" target="_blank" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Wilayah Pengembangan</td>
          <td>7.19 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20RENCANA/2%20Wilayah%20Pengembangan.jpg" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Rencana Jaringan Prasarana</td>
          <td>7.5 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20RENCANA/3%20Rencana%20Jaringan%20Prasarana.jpg" target="_blank" target="_blank">download </a></td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td>4 Rencana Pola Ruang</td>
          <td>8.24 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20RENCANA/4%20Rencana%20Pola%20Ruang.jpg" target="_blank" target="_blank">download </a></td>
        </tr>

        <tr>
          <th scope="row">5</th>
          <td>Kawasan Strategis</td>
          <td>8.84 MB</td>
          <td><a href="http://23.244.65.219/simtaru.kabbdg/download/peta/PETA%20RENCANA/5%20Kawasan%20Strategis.jpg" target="_blank">download </a></td>
        </tr>
        </tbody>
    </table>
{% endblock content %}

dokumen/templates/dokumen/upload.html
{% extends 'simtaru_kabbdg/base_form.html' %}

{% block content %}
    <h2 class="title-style-2">Upload Dokumen<span class="title-under"></span></h2>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        {% if user.is_superuser %}
            <p>{{ form.berkas_publik }} untuk publik</p>
        {% endif %}
        <p><input type="submit" value="Upload"/></p>
    </form>
{% endblock content %}