berita/urls.py
from django.conf.urls import url

from berita import views

urlpatterns = [
    url(r'^$', views.lihat_semua_berita, name='semua_berita'),
    url(r'^detail/(?P<berita_id>\d+)/$', views.lihat_berita, name='sebuah_berita'),
]

kuisioner/urls.py
from django.conf.urls import url

from kuisioner import views

urlpatterns = [
    url(r'^$', views.tampilkan_kuisioner, name='kuisioner'),
    url(r'^token', views.tamu_login),
    url(r'detail/(?P<alasan>\w+)/', views.detail_statistik)
]

simtaru_kabbdg/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', views.profile_view, name='profile'),
    url(r'^grafik/', views.grafik_view, name='grafik'),
    url(r'^kontak/', views.kontak_view, name='kontak'),
    url(r'^peta/', include('lihat_peta.urls', namespace='peta')),
    url(r'^kuisioner/', include('kuisioner.urls', namespace='kuisioner')),
    url(r'^dokumen/', include('dokumen.urls', namespace='dokumen')),
    url(r'^berita/', include('berita.urls', namespace='berita')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kuisioner/models.py
from django.db import models

PILIHAN = (
    ('pendidikan', 'Pendidikan'),
    ('pekerjaan', 'Pekerjaan'),
    ('perijinan', 'Perijinan'),
    ('pemerintahan', 'Pemerintahan'),
)


class Kuisioner(models.Model):
    alasan = models.CharField(
        max_length=50, choices=PILIHAN, default='pendidikan')
    nama = models.CharField(max_length=255)
    email = models.EmailField()
    tlp = models.CharField(max_length=255, default='1111')

kuisioner/forms.py
from django import forms


PILIHAN = (
    ('pendidikan', 'Pendidikan'),
    ('pekerjaan', 'Pekerjaan'),
    ('perijinan', 'Perijinan'),
    ('pemerintahan', 'Pemerintahan'),
)


class KuisionerForm(forms.Form):
    """
    memasukan name email dan alasan,
    password akan dibuat automatis sebagai token yang dikirim ke email
    untuk usernamenya memakai session ID
    """
    alasan = forms.ChoiceField(choices=PILIHAN, widget=forms.RadioSelect)
    nama = forms.CharField(max_length=255)
    tlp = forms.CharField(max_length=255)
    email = forms.EmailField()

kuisioner/views.py
import random
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail


from .models import Kuisioner
from .forms import KuisionerForm


def gen_passwd():
    charset = 'ABCDEF1234567890'
    return ''.join(random.choice(charset) for _ in range(7))


def tampilkan_kuisioner(request):
    """
    Hanya menampilkan kuisioner, view ini juga berfungsi untuk melakukan
    registrasi user. Setelah itu halaman untuk mengisi password ditampilkan.
    user baru dibuat dengan session_id sebagi username
    """
    if request.method == 'POST':
        form = KuisionerForm(request.POST)
        if form.is_valid():
            k = Kuisioner(
                nama=form.cleaned_data['nama'],
                alasan=form.cleaned_data['alasan'],
                email=form.cleaned_data['email'],
                tlp=form.cleaned_data['tlp'],
            )
            k.save()
            password = gen_passwd()
            username = request.session._get_new_session_key()[:10]
            u = User.objects.create_user(
                username, password=password, first_name=form.cleaned_data['nama'])
            u.save()
            request.session['tamu'] = username
            send_mail(
                'Token akses Peta',
                'Untuk mengakses peta silahkan gunakan kode ini: %s' % password,
                'admin@simtaru.kabbdg.go.id',
                [form.cleaned_data['email']]
            )
            return render(request, 'kuisioner/masukan_token.html')
    else:
        form = KuisionerForm()

    return render(request, 'kuisioner/kuisioner.html', {
        'form': form,
    })


def tamu_login(request):
    """
    prosess login untuk tamu setelah itu di redirect ke halaman peta
    """
    username = request.session['tamu']
    password = request.POST.get('token', '')
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        del request.session['tamu']
        request.session.set_expiry(300)
        print "SESSION WILL EXPIRE IN 300 SECONDS"
        return HttpResponseRedirect('/')
    else:
        print "GA LOGIN"
        # TODO: Tampilkan kalo token salah, generate ulang token lalu kirim lagi
        return HttpResponseRedirect('/')
    pass


def detail_statistik(request, alasan):
    ret = []
    k_all = Kuisioner.objects.all().filter(alasan=alasan.lower())

    return render(request, 'kuisioner/detail_stat.html', {'detail': k_all, 'alasan': alasan})

kuisioner/templates/kuisioner/detail_stat.html
{% extends 'simtaru_kabbdg/base_content.html' %}

{% block title %}
Detail Penggunaan
{% endblock title %}

{% block content %}
<h2 class="title-style-2">Peruntukan Peta Berdasarkan {{ alasan }}<span class="title-under"></span></h2>
{% if detail %}
    <table class="table table-style-1">
        <thead>
            <tr>
                <th>Nama</th>
                <th>Email</th>
                <th>Tlp</th>
            </tr>
        </thead>
        <tbody>
            {% for d in detail %}
                <tr>
                    <td>{{ d.nama }}</td>
                    <td>{{ d.email }}</td>
                    <td>{{ d.tlp }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <h3>Belum ada dokumen yang mengakses</h3>
{% endif %}

<a href="{% url 'grafik' %}">
    <button class="btn btn-primary">
        Kembali
    </button>
</a>

{% endblock content %}

kuisioner/templates/kuisioner/kuisioner.html
{% extends "simtaru_kabbdg/base_form.html" %}
{% block content %}
    <h2 class="title-style-2">Silahkan Isi Form Dibawah Ini<span class="title-under"></span></h2>
    <form action="{% url 'kuisioner:kuisioner' %}" class="contact-form ajax-form" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="row">
                            <div class="form-group col-md-4">
                                {{ form.nama.errors }}
                                <label for="id_nama">Nama*</label>
                                {{ form.nama }}
                            </div>
                             <div class="form-group col-md-4">
                                {{ form.email.errors }}
                                <label for="id_email">E-mail*</label>
                                {{ form.email }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.tlp.errors }}
                                <label for="id_tlp">No Handphone*</label>
                                {{ form.tlp }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.alasan.errors }}
                            <label for="id_alasan"><h3>Tujuan Mengakses Peta :</h3></label>
                            {{ form.alasan }}
                        </div>
                        <div class="form-group alerts">
                            <div class="alert alert-success" role="alert">
                            </div>
                            <div class="alert alert-danger" role="alert">
                            </div>
                        </div>
                         <div class="form-group">
                           <button type="submit" class="btn btn-primary pull-right">LANJUTKAN</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
{% endblock content %}

kuisioner/templates/kuisioner/masukan_token.html
{% extends "simtaru_kabbdg/base_form.html" %}
{% block content %}
    <h1>Silahkan memasukan token yang dikirim ke E-Mail anda:</h1>
    <form method="POST" action="/kuisioner/token">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" name="token" type="text" id="token">
        </div>
        <div class="form-group">
           <button type="submit" class="btn btn-primary pull-right">LANJUTKAN</button>
        </div>
    </form>
{% endblock content %}