berita/urls.py
from django.conf.urls import url

from berita import views

urlpatterns = [
    url(r'^$', views.lihat_semua_berita, name='semua_berita'),
    url(r'^detail/(?P<berita_id>\d+)/$', views.lihat_berita, name='sebuah_berita'),
]

dokumen/urls.py
from django.conf.urls import url

from dokumen import views

urlpatterns = [
    url(r'^$', views.daftar_dokumen, name='dokumen'),
    url(r'^download/(?P<dok_id>\d+)/$', views.download_dokumen, name='download'),
    url(r'^upload/$', views.upload_dokumen, name='upload'),
    url(r'^peta_dasar$', views.peta_dasar, name='peta_dasar'),
    url(r'^peta_rencana$', views.peta_rencana, name='peta_rencana'),
]

kuisioner/urls.py
from django.conf.urls import url

from kuisioner import views

urlpatterns = [
    url(r'^$', views.tampilkan_kuisioner, name='kuisioner'),
    url(r'^token', views.tamu_login),
    url(r'detail/(?P<alasan>\w+)/', views.detail_statistik)
]

simtaru_kabbdg/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', views.profile_view, name='profile'),
    url(r'^grafik/', views.grafik_view, name='grafik'),
    url(r'^kontak/', views.kontak_view, name='kontak'),
    url(r'^peta/', include('lihat_peta.urls', namespace='peta')),
    url(r'^kuisioner/', include('kuisioner.urls', namespace='kuisioner')),
    url(r'^dokumen/', include('dokumen.urls', namespace='dokumen')),
    url(r'^berita/', include('berita.urls', namespace='berita')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simtaru_kabbdg/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

simtaru_kabbdg/views.py
from django.shortcuts import render
from berita.models import Berita
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect
from django.db.models import Count

from .forms import LoginForm
from kuisioner.models import Kuisioner
# Create your views here.


def home(request):
    berita = Berita.objects.all()[:4]
    return render(request, 'simtaru_kabbdg/home.html', {'berita': berita})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/')
    else:
        form = LoginForm()
    return render(request, 'simtaru_kabbdg/login.html', {'form': form})


def profile_view(request):
    return render(request, 'simtaru_kabbdg/profile.html')


def kontak_view(request):
    # TODO: prosess kontak form
    if request.method == 'POST':
        return HttpResponseRedirect('/')
    return render(request, 'simtaru_kabbdg/kontak.html')


def grafik_view(request):
    # TODO: better permission handling
    if request.user.is_superuser:
        stat = Kuisioner.objects.values('alasan').annotate(total=Count('alasan')).order_by('alasan')
        return render(request, 'simtaru_kabbdg/grafik.html', {'stat': stat})
    else:
        return HttpResponseRedirect('/')

simtaru_kabbdg/templates/simtaru_kabbdg/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>SIMTARU | Kabupaten Bandung</title>
        <link rel="icon" href="{% static 'simtaru_kabbdg/assets/images/icons/favicon.png' %}" type="image/x-icon" />
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>

        <!-- Bootsrap -->
        <link href="{% static 'simtaru_kabbdg/assets/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'simtaru_kabbdg/assets/lib/jquery/jquery-ui.css' %}" rel="stylesheet"/>

        <!-- Font awesome -->
        <link rel="stylesheet" href="{% static 'simtaru_kabbdg/assets/css/font-awesome.min.css' %}">

        <!-- Owl carousel -->
        <link rel="stylesheet" href="{% static 'simtaru_kabbdg/assets/css/owl.carousel.css' %}">

        <!-- Template main Css -->
        <link rel="stylesheet" href="{% static 'simtaru_kabbdg/assets/css/style.css' %}">

        <!-- Modernizr -->
        <script src="{% static 'simtaru_kabbdg/assets/js/modernizr-2.6.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'simtaru_kabbdg/assets/lib/jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'simtaru_kabbdg/assets/lib/jquery/jquery-ui.js' %}"></script>
        <script type="text/javascript" src="{% static 'simtaru_kabbdg/assets/lib/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block extra_header %}
        {% endblock extra_header %}

    </head>

    <body>

    <header class="main-header">

        <nav class="navbar navbar-static-top">

            <div class="navbar-top">

              <div class="container">
                  <div class="row">

                    <div class="col-sm-6 col-xs-12">


                    </div>

                    <div class="col-sm-6 col-xs-12 text-right">
                        <ul class="list-unstyled list-inline header-contact">
                            <li> <i class="fa fa-phone"></i> <a href="tel:">+022(xxxxx) </a> </li>
                            <li> <i class="fa fa-envelope"></i> <a href="mailto:contact@sadaka.org">contact@simtaru.kabbdg.go.id</a> </li>
                            {% if user.is_authenticated %}
                                <li>
                                    {% if user.first_name %}
                                        {{ user.first_name|upper }}
                                    {% else %}
                                        {{ user.username }}
                                    {% endif %}
                                </li>
                                {% if user.is_superuser %}
                                    <li><a href="/admin">Menu Admin</a></li>
                                {% endif %}
                            {% endif %}

                       </ul>
                    </div>

                  </div>
              </div>

            </div>

            <div class="navbar-main">

              <div class="container">

                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                  </button>

                  <a class="navbar-brand" href="/"><img src="{% static 'simtaru_kabbdg/assets/images/logo.png' %}" alt=""></a>

                </div>

                <div id="navbar" class="navbar-collapse collapse pull-right">
                    <!--Menu-->
                    <ul class="nav navbar-nav">
                        <li><a href="/">HOME</a></li>
                        <li class="has-child"><a href="{% url 'profile' %}">PROFIL SIMTARU</a>
                        </li>
                        <li><a href="/peta">PETA</a></li>
                        <li><a href="{% url 'berita:semua_berita' %}">BERITA</a></li>
                        <li class="has-child">
                            <a href="{% url 'dokumen:dokumen' %}">DOWNLOAD</a>
                            <ul class="submenu">
                                <li class="submenu-item"><a href="{% url 'dokumen:upload' %}">Upload</a></li>
                            </ul>
                        </li>
                        {% if user.is_superuser %}
                            <li><a href="{% url 'grafik' %}">STATISTIK</a></li>
                        {% endif %}
                        <!--li><a href="gallery.php">GALERI</a></li-->
                        <li><a href="{% url 'kontak' %}">KONTAK</a></li>

                        {% if user.is_authenticated %}
                            <li class="submenu-item"><a href="/logout">LOGOUT</a></li>
                        {% else %}
                            <li><a href="/login">LOGIN</a></li>
                        {% endif %}

                    </ul>
                </div> <!-- /#navbar -->

              </div> <!-- /.container -->

            </div> <!-- /.navbar-main -->

        </nav>

    </header> <!-- /. main-header -->
    {% block content_container %}
    {% endblock content_container %}

    <footer class="main-footer">
        <div class="footer-top">
        </div>
        <div class="footer-main">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="footer-col">
                            <h4 class="footer-title">Tentang Aplikasi<span class="title-under"></span></h4>
                            <div class="footer-content">
                                <p>
                                    <strong>Simtaru</strong> iUU Nomor 26 tahun 2007 telah mengamanatkan semua daerah provinsi, kabupaten, dan kota harus mempunyai Rencana Tata Ruang Wilayah (RTRW)  dan Rencana Rinci Tata Ruang agar pembangunan di daerah dapat dilaksanakan dengan baik.  
                                <p>
                                    Untuk mewujudkan penyelenggaraan penataan ruang yang sesuai aturan hukum ternyata pada pemerintah daerah masih dihadapi persoalan-persoalan yang cukup mendasar, diantaranya yang merupakan hal terpenting adalah keterbatasan SDM di dalam memahami dan penyelenggaraan penataan ruang. Dilain pihak tuntutan masyarakat yang didasari atas kesadaran masyarakat akan fungsi dan peran penataan ruang yang baik juga telah meningkat.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="footer-col">
                            <h4 class="footer-title">File Download<span class="title-under"></span></h4>
                            <div class="footer-content">
                                <ul class="tweets list-unstyled">
                                    <li class="tweet"> 
                                        <a href="{% url 'dokumen:dokumen' %}">Download peta dan dokumen</a>
                                    </li>
                                    <li class="tweet"> 
                                        <a href="{% url 'dokumen:peta_dasar' %}">Peta Dasar</a>
                                    </li>
                                    <li class="tweet"> 
                                        <a href="{% url 'dokumen:peta_rencana' %}">Peta Rencana</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="footer-col">
                            <h4 class="footer-title">Kontak Kami <span class="title-under"></span></h4>
                            <div class="footer-content">
                                <div class="contact-items">
                                    <ul class="list-unstyled contact-items-list">
                                        <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-map-marker"></i></span> Jl. Raya Soreang km.17 Komplek Pemda Kabupaten Soreang, Bandung 40912 Jawa Barat</li>
                                        <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-phone"></i></span>(022) 5891-159</li>
                                        <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-envelope"></i></span> contact@simtaru.go.id</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container text-right">
                Copyright © 2017 Simtaru</a>
            </div>
        </div>
    </footer> <!-- main-footer -->

    <!-- owl carouseljavascript file -->
    <script src="{% static 'simtaru_kabbdg/assets/js/owl.carousel.min.js' %}"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>

    </body>
</html>

simtaru_kabbdg/templates/simtaru_kabbdg/base_content.html
{% extends 'simtaru_kabbdg/base.html' %}
{% block content_container %}
    <div class="page-heading text-center">
    <div class="container zoomIn animated">
        <h1 class="page-title">
            {% block title %}
                Judul
            {% endblock title %}
            <span class="title-under"></span>
        </h1>
        <p class="page-description">
            Sistem Informasi Tata Ruang Kabupaten Bandung
        </p>
    </div>

    </div>
    <div class="main-container fadeIn animated">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
{% endblock content_container %}

simtaru_kabbdg/templates/simtaru_kabbdg/base_form.html
{% extends 'simtaru_kabbdg/base.html' %}
{% block content_container %}
    <div class="main-container fadeIn animated">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-sm-12 col-form">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </div>
{% endblock content_container %}

simtaru_kabbdg/templates/simtaru_kabbdg/grafik.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% load staticfiles %}
{% block title %}
    STATISTIK PENGGUNAAN
{% endblock title %}
{% block extra_header %}
    <script type="text/javascript" src="{% static 'simtaru_kabbdg/assets/lib/highcharts/highcharts.js' %}"></script>
{% endblock extra_header %}

{% block content %}
    {% if stat %}
    <script type="text/javascript">
        var chart1; // globally available
        $(document).ready(function() {
              chart1 = new Highcharts.Chart({
                 chart: {
                    renderTo: 'container',
                    type: 'column',

                 },
                 title: {
                    text: 'Grafik Penggunaan Peta '
                 },
                 xAxis: {
                    categories: [ 'Pekerjaan', 'Pemerintahan', 'Pendidikan', 'Perijinan']
                 },
                 yAxis: {
                    title: {
                       text: 'Jumlah User'
                    }
                 },
                 series:
                    [
                      {
                          name: 'Jumlah Pengguna',
                          data: [
                            {% for s in stat %}
                                {{ s.total }} ,
                            {% endfor %}
                          ]
                      },
                    ],
                 plotOptions: {
                    series: {
                        cursor: 'pointer',
                        point: {
                            events: {
                                click: function(){
                                    location.href = {% url 'kuisioner:kuisioner' %}+ 'detail/' + this.category
                                }
                            }
                        }
                    }
                 }
              });
        });
    </script>

    <div id='container'></div>
    {% else %}
        <h2>Belum ada data</h2>
    {% endif %}
{% endblock content %}

simtaru_kabbdg/templates/simtaru_kabbdg/home.html
{% extends "simtaru_kabbdg/base.html" %}
{% load staticfiles %}
{% block content_container %}
<!-- Carousel
    ================================================== -->
    <div id="homeCarousel" class="carousel slide carousel-home" data-ride="carousel">

          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#homeCarousel" data-slide-to="1"></li>
            <li data-target="#homeCarousel" data-slide-to="2"></li>
          </ol>

          <div class="carousel-inner" role="listbox">

            <div class="item active">

              <img src="{% static 'simtaru_kabbdg/assets/images/slider/home-slider-1.jpg' %}" alt="">

              <div class="container">

                <div class="carousel-caption">

                  <h2 class="carousel-title bounceInDown animated slow">Selamat Datang Di Aplikasi SIMTARU</h2>
                  <h4 class="carousel-subtitle bounceInUp animated slow ">Kabupaten Bandung</h4>
                  <!-- <a href="#" class="btn btn-lg btn-secondary hidden-xs bounceInUp animated slow" data-toggle="modal" data-target="#donateModal">SELENGKAPNYA..</a> -->

                </div> <!-- /.carousel-caption -->

              </div>

            </div> <!-- /.item -->

            <div class="item ">

              <img src="{% static 'simtaru_kabbdg/assets/images/slider/home-slider-2.jpg' %}" alt="">
              <div class="container">

                <div class="carousel-caption">

                  <!-- <a href="#" class="btn btn-lg btn-secondary hidden-xs bounceInUp animated slow" data-toggle="modal" data-target="#donateModal">SELENGKAPNYA..</a> -->

                </div> <!-- /.carousel-caption -->

              </div>
            </div> <!-- /.item -->


            <div class="item ">

              <img src="{% static 'simtaru_kabbdg/assets/images/slider/home-slider-3.jpg' %}" alt="">

              <div class="container">

                <div class="carousel-caption">

                  <h2 class="carousel-title bounceInDown animated slow" ></h2>
                  <h4 class="carousel-subtitle bounceInUp animated slow"></h4>
                  <a href="/peta" class="btn btn-lg btn-secondary hidden-xs bounceInUp animated slow">Peta Kab.Bandung</a>

                </div> <!-- /.carousel-caption -->

              </div>

            </div> <!-- /.item -->

          </div>

          <a class="left carousel-control" href="#homeCarousel" role="button" data-slide="prev">
            <span class="fa fa-angle-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>

          <a class="right carousel-control" href="#homeCarousel" role="button" data-slide="next">
            <span class="fa fa-angle-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>

    </div><!-- /.carousel -->

    </div><!-- /.home-reasons -->

    <div class="section-home about-us fadeIn animated">

        <div class="container">

            <div class="row">

                <div class="col-md-3 col-sm-6">

                  <div class="about-us-col">

                        <div class="col-icon-wrapper">
                          <iframe width="210" height="220"
                            src="https://www.youtube.com/embed/YPe5JGJdoPE">
                         </iframe>
                      </div>
                      <br>
                         <a href="#" class="btn btn-primary"> Tentang Kab.Bandung</a>
                  </div>

                </div>

                <div class="col-md-3 col-sm-6">

                  <div class="about-us-col">

                        <div class="col-icon-wrapper">
                          <img src="{% static 'simtaru_kabbdg/assets/images/icons/make-donation-icon.png' %}" alt="">
                        </div>
                        <h3 class="col-title">Peta</h3>
                        <div class="col-details">

                          <p>Peta Kabupaten Bandung yang disajikan dalam bentuk peta dasar, peta administrasi dan peta rencana</p>

                        </div>
                        <a href="/peta" class="btn btn-primary"> Selengkapnya.. </a>

                  </div>

                </div>

                <div class="col-md-3 col-sm-6">

                  <div class="about-us-col">

                        <div class="col-icon-wrapper">
                          <img src="{% static 'simtaru_kabbdg/assets/images/icons/help-icon.png' %}" alt="">
                        </div>
                        <h3 class="col-title">Download</h3>
                        <div class="col-details">

                          <p>Download Bermacam-macam dokumen peta dan dokumen lainnya..</p>

                        </div>
                        <a href="indexdownload.php" class="btn btn-primary"> Selengkapnya.. </a>

                  </div>

                </div>

                <div class="col-md-3 col-sm-6">

                  <div class="about-us-col">

                        <div class="col-icon-wrapper">
                          <img src="{% static 'simtaru_kabbdg/assets/images/icons/programs-icon.png' %}" alt="">
                        </div>
                        <h3 class="col-title">Kontak Kami</h3>
                        <div class="col-details">

                          <p>Alamat kami di kantor Pemda Kabupaten Bandung.</p>

                        </div>
                        <a href="contact.php" class="btn btn-primary"> Selengkapnya.. </a>

                  </div>

                </div>


            </div>

        </div>

    </div> <!-- /.about-us -->

    <!-- Tampilkan Berita -->
    <div class="container gallery fadeIn animated">

        <div class="container">

            <h2 class="title-style-1">Berita Terbaru<span class="title-under"></span></h2>
            <div class="row">
                {% for b in berita %}
                <div class="col-md-3 col-sm-6">
                    <div class="cause">
                        <img src="{{ b.gambar.url }}" alt="" class="cause-img" height="150" width="150"/>
                        <h4 class="cause-title">
                            <a href="#">
                                {{ b.judul }}
                            </a>
                        </h4>
                        <div class="cause-details">
                            {{ b.updated }}
                            <br>
                            <br>
                            <p>{{ b.berita_pendek }}...</p>
                        </div>
                        <div class="btn-holder text-center">
                          <a href="{% url 'berita:sebuah_berita' b.id %}" class="btn btn-primary" data-toggle="modal"> SELENGKAPNYA..</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            <!--<h3>Belum Ada Berita</h3>-->
            </div>
        </div>
    </div> <!-- /.our-causes -->
{% endblock content_container %}

simtaru_kabbdg/templates/simtaru_kabbdg/kontak.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% load staticfiles %}
{% block title %}
    Profil Simtaru
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-7 col-sm-12 col-form">

            <h2 class="title-style-2">Silahkan Isi Form Dibawah Ini<span class="title-under"></span></h2>

            <form action="{% url 'kontak' %}" class="contact-form ajax-form" method="post">
                {% csrf_token %}
                <div class="row">

                    <div class="form-group col-md-6">
                        <input type="text" name="name" class="form-control" placeholder="Nama*" required>
                    </div>

                     <div class="form-group col-md-6">
                        <input type="email" name="email" class="form-control" placeholder="E-mail*" required>
                    </div>

                </div>
                <div class="form-group">
                    <textarea name="message" rows="5" class="form-control" placeholder="Message*" required></textarea>
                </div>
                <div class="form-group alerts">

                    <div class="alert alert-success" role="alert">

                    </div>

                    <div class="alert alert-danger" role="alert">

                    </div>

                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary pull-right">Kirim Pesan</button>
                </div>
                <div class="clearfix"></div>
            </form>

        </div>
        <div class="col-md-4 col-md-offset-1 col-contact">

            <h2 class="title-style-2"> Aplikasi Simtaru <span class="title-under"></span></h2>
            <div class="contact-items">

                <ul class="list-unstyled contact-items-list">
                    <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-map-marker"></i></span>
                        Jl. Raya Soreang km.17 Komplek Pemda Kabupaten
                        Soreang, Bandung 40912
                        Jawa Barat
                    </li>
                    <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-phone"></i></span>(022) 5891-159</li>

                    <li class="contact-item"> <span class="contact-icon"> <i class="fa fa-envelope"></i></span> contact@simtaru.go.id</li>
                </ul>
            </div>



        </div>
    </div>
{% endblock content %}

simtaru_kabbdg/templates/simtaru_kabbdg/login.html
{% extends 'simtaru_kabbdg/base_form.html' %}
{% block content %}
<h2 class="title-style-2">Silahkan Login<span class="title-under"></span></h2>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Login"/></p>
</form>
{% endblock content %}

simtaru_kabbdg/templates/simtaru_kabbdg/profile.html
{% extends 'simtaru_kabbdg/base_content.html' %}
{% load staticfiles %}
{% block title %}
    Profil Simtaru
{% endblock title %}

{% block content %}
    <div class="row fadeIn animated">

                <div class="col-md-6">

                    <img src="{% static 'simtaru_kabbdg/assets/images/about-us.jpg' %}" alt="" class="img-responsive">

                </div>

                <div class="col-md-6">

                    <h2 class="title-style-2">Tentang Simtaru <span class="title-under"></span></h2>

                    <p><strong>Simtaru</strong> Menurut UU Nomor 26 tahun 2007 telah mengamanatkan semua daerah provinsi, kabupaten, dan kota harus mempunyai Rencana Tata Ruang Wilayah (RTRW)  dan Rencana Rinci Tata Ruang agar pembangunan di daerah dapat dilaksanakan dengan baik.
                    </p>
                    <p>
                     Untuk mewujudkan penyelenggaraan penataan ruang yang sesuai aturan hukum ternyata pada pemerintah daerah masih dihadapi persoalan-persoalan yang cukup mendasar, diantaranya yang merupakan hal terpenting adalah keterbatasan SDM di dalam memahami dan penyelenggaraan penataan ruang. Dilain pihak tuntutan masyarakat yang didasari atas kesadaran masyarakat akan fungsi dan peran penataan ruang yang baik juga telah meningkat.
                    </p>

                </div>

            </div>
{% endblock content %}